export default {
  MOTION_GROUP_IDLE: 'Idle',
  MOTION_GROUP_TAP_BODY: 'TapBody',

  HIT_AREA_NAME_HEAD: 'Head',
  HIT_AREA_NAME_BODY: 'Body',

  PRIORITY_NONE: 0,
  PRIORITY_IDLE: 1,
  PRIORITY_NORMAL: 2,
  PRIORITY_FORCE: 3,

  RENDER_TARGET_WIDTH: 600,
  RENDER_TARGET_HEIGHT: 800,
}
