export default {
  MOTION_GROUP_IDLE: 'MOTION_GROUP_IDLE',
  MOTION_GROUP_TAP_BODY: 'MOTION_GROUP_TAP_BODY',

  HIT_AREA_NAME_HEAD: 'HIT_AREA_NAME_HEAD',
  HIT_AREA_NAME_BODY: 'HIT_AREA_NAME_BODY',

  PRIORITY_NONE: 0,
  PRIORITY_IDLE: 1,
  PRIORITY_NORMAL: 2,
  PRIORITY_FORCE: 3,

  RENDER_TARGET_WIDTH: 600,
  RENDER_TARGET_HEIGHT: 800,
}
