export default {
  VIEW_SCALE: 1.0,
  VIEW_MAX_SCALE: 2.0,
  VIEW_MIN_SCALE: 0.8,

  VIEW_LOGICAL_LEFT: -1.0,
  VIEW_LOGICAL_RIGHT: 1.0,
  VIEW_LOGICAL_BOTTOM: -1.0,
  VIEW_LOGICAL_TOP: 1.0,

  VIEW_LOGICAL_MAX_LEFT: -2.0,
  VIEW_LOGICAL_MAX_RIGHT: 2.0,
  VIEW_LOGICAL_MAX_BOTTOM: -2.0,
  VIEW_LOGICAL_MAX_TOP: 2.0,
}
